# Generated by Django 3.2.8 on 2021-10-24 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
