# Generated by Django 3.2.8 on 2021-10-25 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20211024_1511'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherdata',
            table='weather_data',
        ),
    ]
